# .pre-commit-config.yaml file for https://github.com/zxdavb

repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(ramses.*/.+)?[^/]+\.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
        files: ^ramses.*/.+\.py$
        exclude: ^ramses.*/tests\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
